### ISSUE TITLE
can not be used on window 10

### ISSUE THREAD

**Issue by ZhangYan2580** [Rascalov/Anki-Simple-Forvo-Audio#12]
错误
发生了一个错误。请在启动Anki时按住「Shift」键临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki， 请重复上述步骤直至找到引起错误的插件。 找到引起错误的插件后，请反馈给插件作者。 调试信息：
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-18 16:07:01

Caught exception:
Traceback (most recent call last):
  File "C:\Users\19737\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 155, in <lambda>
    addButton.clicked.connect(lambda: self.insertIntoCard(ankiAudioObject))
  File "C:\Users\19737\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 175, in insertIntoCard
    fullpath = self.getDefinteConfigPath() + AnkiAudioGlobals.TEMP_FILE_PREFIX + ankiAudioObject.getBucketFilename()
  File "C:\Users\19737\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 203, in getDefinteConfigPath
    if(configPath[-1] != "\\" or configPath[-1] !="/"):
IndexError: string index out of range

**Comment by ZhangYan2580** [comment]
> Need you to be more specific. I tested on W10 Vm (2.1.54 QT5) and all seems well ![18072003171129](https://user-images.githubusercontent.com/31393063/179574307-e6b36ac6-fb6c-4080-bb7b-d2cede2cd135.png) What is the specific issue?

the old plugin can not the audio, but new version can be used on anki 
when i try to add audio to card, letters as follows appear.

错误
发生了一个错误。请在启动Anki时按住「Shift」键临时禁用插件加载。 如仅在插件启用时出错，请使用「工具」>「插件」功能禁用部分插件后重启Anki， 请重复上述步骤直至找到引起错误的插件。 找到引起错误的插件后，请反馈给插件作者。 调试信息：
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-18 20:07:59

Caught exception:
Traceback (most recent call last):
  File "C:\Users\19737\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 155, in <lambda>
    addButton.clicked.connect(lambda: self.insertIntoCard(ankiAudioObject))
  File "C:\Users\19737\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 175, in insertIntoCard
    fullpath = self.getDefinteConfigPath() + AnkiAudioGlobals.TEMP_FILE_PREFIX + ankiAudioObject.getBucketFilename()
  File "C:\Users\19737\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 203, in getDefinteConfigPath
    if(configPath[-1] != "\\" or configPath[-1] !="/"):
IndexError: string index out of range

**Comment by EliasDonhn** [comment]
I also have the same issue.
I hope you can solve this for us.
Thank you very much.

**Comment by ZhangYan2580** [comment]
solution

C:\\Users\\Administrator\\AppData\\Roaming\\Anki2\\yourankiaccountname\\collection.media
set it in the setting

**Comment by EliasDonhn** [comment]
could you tell me the way to fix it? I don't understand how to do next.

**Comment by EliasDonhn** [comment]
> solution
> 
> C:\Users\Administrator\AppData\Roaming\Anki2\yourankiaccountname\collection.media set it in the setting

Could you help me how to fix it. I don't know how to set it T_T
