### ISSUE TITLE
The add-on suddenly stopped working

### ISSUE THREAD

**Issue by Expertium** [Rascalov/Anki-Simple-Forvo-Audio#43]
And by "suddenly" I mean "it worked literally 5 seconds ago"

```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045

Traceback (most recent call last):
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\560814150\ForvoTts.py", line 148, in start_lookup
    results.extend(lookup_word_lingua_libre(self.textBox.text(), self.languageSelectBox.currentText().split("_")[1]))
  File "C:\Users\Andrew\AppData\Roaming\Anki2\addons21\560814150\bs4Scraper.py", line 174, in lookup_word_lingua_libre
    links = page.select("a[href^='/wiki/Q']")
AttributeError: 'NoneType' object has no attribute 'select'

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2023-10-21T17:34, 'None', '']
Advanced Review Bottom Bar ['1136455830', 2024-08-22T14:04, 'None', mod]
AnkiConnect ['2055492159', 2024-07-26T07:55, 'None', '']
FSRS Helper Postpone  Advance  Load Balance  Easy Days  Disperse Siblings ['759844606', 2024-09-17T14:14, 'None', mod]
Incremental Reading v4119 unofficial clone ['999215520', 2023-11-22T20:54, 'None', '']
Randomize Fonts New ['82628558', 2023-04-16T16:59, 'None', mod]
Remove Duplicate Cards ['95590040', 2024-09-10T17:46, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T04:43, 'None', '']
Simple Forvo Audio Downloader ['560814150', 2024-09-08T16:03, 'None', mod]

===IDs of active AnkiWeb add-ons===
1136455830 1771074083 2055492159 560814150 759844606 82628558 874215009 95590040 999215520

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Adjust Sound Volume ['2123044452', 2023-12-25T17:00, 'None', mod]
Anki Leaderboard - Compete with friends to boost motivation Fork by Shige ['175794613', 2024-09-15T21:18, 'None', mod]
AnkiWebView Inspector ['31746032', 2023-06-27T22:26, 'None', '']
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-09-14T09:04, 'None', '']
Enhanced Cloze for Anki 21 ['1990296174', 2023-09-10T21:48, 'None', '']
Freshness - Randomize CSS styles ['1369362778', 2023-04-23T23:39, 'None', '']
Image Occlusion Enhanced ['1374772155', 2022-04-09T10:15, 'None', '']
Image Style Editor ['1593969147', 2021-12-17T10:01, 'None', mod]
Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2020-03-29T09:26, 'None', '']
Randomize Fonts new ['1696775372', 2023-12-18T05:11, 'None', mod]
Reviews Visualizer ['556289348', 2023-12-15T15:24, 'None', '']
Search Stats Extended ['1613056169', 2024-08-24T14:12, 'None', '']
The KING of Button Add-ons ['374005964', 2024-01-27T13:19, 'None', mod]
True Retention ['613684242', 2017-11-19T23:43, 'None', '']
Yomichan Forvo Server ['580654285', 2024-07-16T01:36, 'None', '']
anki-forvo-dl - Forvo Pronunciation Downloader fully automatic ['858591644', 2024-08-10T05:15, 'None', '']
export cardsnotes from browser with metadata to csv or xlsx ['1967530655', 2024-03-28T16:16, 'None', '']
```

**Comment by Expertium** [comment]
Nevermind, it just magically fixed itself
